### ISSUE TITLE
Failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call

### ISSUE THREAD

**Issue by erbridge** [go-gandi/terraform-provider-gandi#105]
When attempting to `terraform apply` a simple `gandi_domain` update:

```
╷
│ Error: Plugin did not respond
│
│   with gandi_domain.domain,
│   on main.tf line 1, in resource "gandi_domain" "domain":
│    1: resource "gandi_domain" "domain" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-gandi_v2.0.0 plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 63 [running]:
github.com/go-gandi/terraform-provider-gandi/gandi.expandContact(0x10101a860, 0x1400007cc40, 0x5)
	github.com/go-gandi/terraform-provider-gandi/gandi/structures_domain.go:62 +0x8f8
github.com/go-gandi/terraform-provider-gandi/gandi.resourceDomainUpdate(0x1400058c000, 0x100f08a80, 0x14000356d20, 0xffffffffffffffff, 0x1400012f6b8)
	github.com/go-gandi/terraform-provider-gandi/gandi/resource_domain.go:219 +0x384
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000202fc0, 0x1010707b8, 0x1400005b9c0, 0x1400058c000, 0x100f08a80, 0x14000356d20, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:363 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000202fc0, 0x1010707b8, 0x1400005b9c0, 0x1400071cd00, 0x1400042d800, 0x100f08a80, 0x14000356d20, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:475 +0x2c0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140001a9488, 0x1010707b8, 0x1400005b9c0, 0x140005054f0, 0x100de73e7, 0x12, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0x870
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001f0500, 0x101070860, 0x1400005b9c0, 0x1400020a150, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x338
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10101a700, 0x140001f0500, 0x101070860, 0x1400046af00, 0x14000648300, 0x0, 0x101070860, 0x1400046af00, 0x14000105500, 0x984)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400034efc0, 0x101077cd8, 0x14000418a80, 0x14000208000, 0x140004007e0, 0x1014aa580, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x1400034efc0, 0x101077cd8, 0x14000418a80, 0x14000208000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000306260, 0x1400034efc0, 0x101077cd8, 0x14000418a80, 0x14000208000)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

Error: The terraform-provider-gandi_v2.0.0 plugin crashed!
```

The Terraform:

```tf
resource "gandi_domain" "domain" {
  name = "domain.name"

  autorenew = true

  owner {
    <snip>
  }
}

resource "gandi_livedns_domain" "domain" {
  name = "domain.name"

  automatic_snapshots = true
}
```

**Comment by nlewo** [comment]
Thanks for this bug report.

Is the value of `given_name` an empty string in your `owner` block?

**Comment by nlewo** [comment]
@erbridge I think https://github.com/go-gandi/terraform-provider-gandi/pull/107 should fix your issue.

Would you be able to try it?

**Comment by erbridge** [comment]
How do I specify an unreleased provider version? Sorry - not had to do that before.

**Comment by erbridge** [comment]
> Is the value of given_name an empty string in your owner block?

No, it has a value.

**Comment by nlewo** [comment]
@erbridge You can run `make build` on my branch to produce an executable in your current directory. Then, you can copy this executable to your Terraform directory (`your-terraform-workspace/.terraform/providers/github/go-gandi/gandi/2.0.0-rc3/linux_amd64/`) and run `terraform init`. The news provider should be be used.

(maybe there is a more convenient way...)

> No, it has a value.

:thinking:

**Comment by erbridge** [comment]
`terraform init` wants to fetch a new version from the registry every time 🤔
